#!/bin/bash

#select only the searches
#of searches cut everything except the keyword
#group by keyword
#return count

result=$(grep '/search' ./log/* | cut -d ":" -f 6 | sort | uniq | wc -l)

echo "TotalNumberOfKeyWordsSearched ${result}"
